name: Static Website Hosting to S3 Bucket

on: [push]

jobs:
deploy-to-s3:
runs-on: ubuntu-latest
steps:

name: checkout repository code
uses: actions/checkout@v3

name: AWS credential
uses: aws-actions/configure-aws-credentials@v2
with:
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
aws-region: us-east-1

name: push to aws s3 bucket
runs: aws s3 sync . s3://aws-s3-bucket-zain
